# coding: utf-8

"""
    Classics Proxy API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import classics_proxy_client
from classics_proxy_client.models.inline_response2001_collections import InlineResponse2001Collections  # noqa: E501
from classics_proxy_client.rest import ApiException

class TestInlineResponse2001Collections(unittest.TestCase):
    """InlineResponse2001Collections unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse2001Collections
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = classics_proxy_client.models.inline_response2001_collections.InlineResponse2001Collections()  # noqa: E501
        if include_optional :
            return InlineResponse2001Collections(
                authors = '0', 
                data_id = '0', 
                title = '0', 
                zn_title = '0'
            )
        else :
            return InlineResponse2001Collections(
        )

    def testInlineResponse2001Collections(self):
        """Test InlineResponse2001Collections"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
