# coding: utf-8

"""
    Classics Proxy API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import classics_proxy_client
from classics_proxy_client.api.default_api import DefaultApi  # noqa: E501
from classics_proxy_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = classics_proxy_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_itkc_all_text_meta(self):
        """Test case for itkc_all_text_meta

        """
        pass

    def test_itkc_corpora(self):
        """Test case for itkc_corpora

        """
        pass

    def test_itkc_meta(self):
        """Test case for itkc_meta

        """
        pass

    def test_itkc_series(self):
        """Test case for itkc_series

        """
        pass

    def test_itkc_text(self):
        """Test case for itkc_text

        """
        pass


if __name__ == '__main__':
    unittest.main()
